Set node/edit to use admin theme (Gin).
localgovdrupal/localgov_microsites pull request #87
Opened 2022-05-19 15:20 UTC by finnlewis

2022-05-19 15:21 UTC, finnlewis commented
This look ok @ekes ?

2022-05-20 13:03 UTC, ekes commented
So this has got the permission for media in it too?

And those permissions allow anyone to delete or edit the media from any other user/site?

2022-05-20 13:06 UTC, ekes requested changes

2022-05-20 13:06 UTC, ekes commented on config/install/user.role.authenticated.yml
> +  - 'access fontawesome additional settings'
Do they need this too?

2022-05-20 13:06 UTC, ekes commented on config/install/user.role.authenticated.yml
> +  - 'delete media'
Guessing no one should have access to delete media really, just remove it from your content.

2022-05-20 13:06 UTC, ekes commented on config/install/user.role.authenticated.yml
> +  - 'edit any document media'
I can see we might need to do something for editing media that is attached to content that is attached to a group that isn't _owned_ by the user, but again not sure this is the way or needs to be done now.

2022-05-20 13:06 UTC, ekes commented on config/install/user.role.authenticated.yml
> +  - 'view all media revisions'
We've also generally been hiding revisions to keep things simpler so my guess is we don't want revisions here either.

2022-05-20 13:07 UTC, ekes commented
I'm guessing there's another issue about media permissions somewhere that should also be tagged?

2022-05-20 15:36 UTC, finnlewis commented
@ekes I removed those permissions. Looking better?

2022-05-20 15:39 UTC, ekes approved these changes
Looks better. Can we tag an issue to review the media permissions at some point though? I assume there is one, but if not spin out a follow-up.

2022-05-20 15:42 UTC, finnlewis commented
Sorry - just tested again - it does need 'edit any image media'

2022-05-20 15:45 UTC, finnlewis commented
> I'm guessing there's another issue about media permissions somewhere that should also be tagged?

https://github.com/localgovdrupal/localgov_microsites/issues/88

2022-05-20 15:45 UTC, merged